# Generated by Django 4.2.6 on 2023-12-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_item_date_item_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
