# Generated by Django 4.2.6 on 2023-12-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_customer_item_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
